spring.application.name=Spring Chat
spring.datasource.url = jdbc:postgresql://localhost:5432/springchat
spring.datasource.username = postgres
spring.datasource.password = stonedcat
spring.jpa.hibernate.ddl-auto = create
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database = postgresql
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size = 2000MB
spring.servlet.multipart.max-request-size = 2000MB
server.port = 80
